"""empty message

Revision ID: 121a6497a298
Revises: f7d5e22dae0f
Create Date: 2022-10-20 03:37:58.814110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121a6497a298'
down_revision = 'f7d5e22dae0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'anywhere',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos', 'anywhere',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
