"""empty message

Revision ID: 308487e62445
Revises: c209ec0b85c1
Create Date: 2022-10-11 19:25:36.608565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308487e62445'
down_revision = 'c209ec0b85c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiencias', sa.Column('description', sa.String(length=250), nullable=False))
    op.alter_column('experiencias', 'fecha',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('experiencias', 'anywhere',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiencias', 'anywhere',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('experiencias', 'fecha',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('experiencias', 'description')
    # ### end Alembic commands ###
