"""empty message

Revision ID: 4e5ac9ac46b1
Revises: 121a6497a298
Create Date: 2022-10-24 04:19:40.040525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5ac9ac46b1'
down_revision = '121a6497a298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiencias', sa.Column('image_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiencias', 'image_url')
    # ### end Alembic commands ###
