"""empty message

Revision ID: 4f341373051b
Revises: eb1efe0dde46
Create Date: 2022-10-04 19:09:23.192068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f341373051b'
down_revision = 'eb1efe0dde46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('usuarios_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'eventos', 'usuario', ['usuarios_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventos', type_='foreignkey')
    op.drop_column('eventos', 'usuarios_id')
    # ### end Alembic commands ###
