"""empty message

Revision ID: 573e05e80615
Revises: 64b3ac7c9534
Create Date: 2022-11-01 01:10:44.055429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573e05e80615'
down_revision = '64b3ac7c9534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('image_url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'image_url')
    # ### end Alembic commands ###
