"""empty message

Revision ID: 66a65edae790
Revises: 40aa35fdee07
Create Date: 2022-10-04 17:05:21.868970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a65edae790'
down_revision = '40aa35fdee07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiencias', sa.Column('anywhere', sa.Boolean(), nullable=False))
    op.add_column('experiencias', sa.Column('fecha', sa.String(length=80), nullable=False))
    op.add_column('experiencias', sa.Column('indoor', sa.Boolean(), nullable=True))
    op.add_column('experiencias', sa.Column('lugar', sa.String(length=120), nullable=False))
    op.add_column('experiencias', sa.Column('outdoor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiencias', 'outdoor')
    op.drop_column('experiencias', 'lugar')
    op.drop_column('experiencias', 'indoor')
    op.drop_column('experiencias', 'fecha')
    op.drop_column('experiencias', 'anywhere')
    # ### end Alembic commands ###
