"""empty message

Revision ID: 7245f8fb89bc
Revises: 64b3ac7c9534
Create Date: 2022-10-31 03:56:01.082654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7245f8fb89bc'
down_revision = '64b3ac7c9534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('imagen', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'imagen')
    # ### end Alembic commands ###
