"""empty message

Revision ID: 81dc82343fdf
Revises: 22afcdfafc26
Create Date: 2022-11-04 00:50:44.036592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81dc82343fdf'
down_revision = '22afcdfafc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('experiencias_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiencias_id'], ['experiencias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
