"""empty message

Revision ID: 84404d9bd1d2
Revises: 66a65edae790
Create Date: 2022-10-04 17:44:23.516268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84404d9bd1d2'
down_revision = '66a65edae790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('apellido', sa.String(length=120), nullable=False))
    op.add_column('usuario', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('nombre', sa.String(length=120), nullable=False))
    op.add_column('usuario', sa.Column('password', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'password')
    op.drop_column('usuario', 'nombre')
    op.drop_column('usuario', 'edad')
    op.drop_column('usuario', 'apellido')
    # ### end Alembic commands ###
