"""empty message

Revision ID: d298ba525c39
Revises: 
Create Date: 2022-10-06 02:49:32.534505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd298ba525c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=80), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('anywhere', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=80), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('anywhere', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('eventos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eventos_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitados')
    op.drop_table('experiencias')
    op.drop_table('eventos')
    op.drop_table('usuario')
    # ### end Alembic commands ###
