"""empty message

Revision ID: eb1efe0dde46
Revises: 84404d9bd1d2
Create Date: 2022-10-04 18:25:16.134997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1efe0dde46'
down_revision = '84404d9bd1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiencias', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'experiencias', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiencias', type_='foreignkey')
    op.drop_column('experiencias', 'usuario_id')
    # ### end Alembic commands ###
