"""empty message

Revision ID: f7d5e22dae0f
Revises: 308487e62445
Create Date: 2022-10-13 14:38:38.440562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d5e22dae0f'
down_revision = '308487e62445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('description', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'description')
    # ### end Alembic commands ###
